language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

services:
  - memcached
  - mysql

addons:
  apt:
    packages:
    - rcs

before_install:
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_script:
  - ./test/travis.sh

script: vendor/bin/phpunit --debug

notifications:
    irc: "irc.freenode.org#midgard"
