language: php

cache:
    directories:
        - $HOME/.composer/cache

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 8.0

services:
  - memcached
  - mysql

addons:
  apt:
    packages:
    - rcs

before_install:
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
  - travis_retry composer install
  - sudo chown -R travis var/

script: vendor/bin/phpunit --debug
